auto_mapper_plus:
  options:
    create_unregistered_mappings: true
    skip_constructor: true
    use_substitution: true
    ignore_null_properties: false
    # Note that this should be the service name, and not necessarily the
    # FQCN.
    property_accessor: AutoMapperPlus\AutoMapperPlusBundle\PropertyAccessor\SymfonyPropertyAccessorBridge
