nelmio_api_doc:
  documentation:
    info:
      title: ToDo List CRUD
      description: App about personal developing
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
